nginx:
  container_name: c_nginx
  image: dmp1ce/nginx-proxy-letsencrypt
  restart: on-failure:5
  ports:
   - 80:80
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro

meteor:
  container_name: c_meteor_1
  image: gmanjapan/meteor
  restart: on-failure:5
  ports:
   - "3000:80"
  links:
   - mongo
  volumes_from:
    - data
  volumes:
   - ./backup:/backup
  environment:
   - REPO=https://github.com/greggman/vertexshaderart
   - ROOT_URL=http://192.168.99.100:3000
   - IMAGE_PATH=/data/images
   - VIRTUAL_HOST=local.vertexshaderart.com
   - LETSENCRYPT_HOST=local.vertexshaderart.com
   - LETSENCRYPT_EMAIL=letsencrypt@greggman.com
  env_file:
   - ./settings/settings-local.env
data:
  container_name: c_data_1
  image: cogniteev/echo
  volumes:
   - /data/images
   - /data/db
mongo:
  container_name: c_mongo_1
  image: mongo
  restart: on-failure:5
  ports:
   - "127.0.0.1:27017:27017"
  volumes_from:
   - data
  volumes:
   - ./backup:/backup

#   - APP_DIR=/appgit/server/vertexshaderart


