proxy:
  container_name: c_proxy
  image: joshix/caddy:v0.9.1
  restart: on-failure:5
  ports:
   - 80:80
   - 443:443
  volumes:
   - ../files/save/caddy:/.caddy:rw
   - ../files/config/caddy:/var/www/html:ro

meteor:
  container_name: c_meteor_1
  image: ulexus/meteor
  restart: on-failure:5
  ports:
   - "127.0.0.1:3000:80"
  links:
   - mongo
  volumes_from:
    - data
  volumes:
   - ./backup:/backup
  environment:
   - REPO=https://github.com/greggman/vertexshaderart
   - ROOT_URL=https://www.vertexshaderart.com
   - IMAGE_PATH=/data/images
   - RELEASE=1.5.2.2
   - METEOR_ALLOW_SUPERUSER=true
  env_file:
   - ../files/config/meteor/settings.env

data:
  container_name: c_data_1
  image: cogniteev/echo
  volumes:
   - /data/images
   - /data/db

mongo:
  container_name: c_mongo_1
  image: mongo:3.2-jessie
  restart: on-failure:5
  ports:
   - "127.0.0.1:27017:27017"
  volumes_from:
   - data
  volumes:
   - ../backup:/backup

#   - APP_DIR=/appgit/server/vertexshaderart


